[template]
src = "nginx.tmpl"
dest = "/etc/nginx/conf.d/default.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/backends",
  "/frontends",
]
#check_cmd = "/usr/sbin/nginx -t -c {{.src}}"
reload_cmd = "nginx -s reload"
